name: Scoverage Sample Build

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "openjdk@1.17.0"

    - name: Run Tests with Coverage
      run: sbt clean coverage test coverageReport

    - name: Upload coverage to Qlty
      uses: qltysh/qlty-action/coverage@v2
      with:
        token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        files: target/scala-3.3.2-RC1/coverage-report/cobertura.xml
        add-prefix: src/main/scala/
